# Generated by Django 5.2.17 on 2026-09-20 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=50)),
                ('family_number', models.CharField(blank=True, max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='profile_photos/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Other', 'Other')], max_length=20)),
                ('currently_pregnant', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=150)),
                ('bpl', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(max_length=15)),
                ('bpl_number', models.CharField(blank=True, max_length=100)),
                ('ayushman_card_number', models.CharField(blank=True, max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('abha_number', models.CharField(blank=True, max_length=100)),
                ('ayushman_card_file', models.FileField(blank=True, null=True, upload_to='documents/ayushman/')),
                ('aadhaar_card_file', models.FileField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('abha_card_file', models.FileField(blank=True, null=True, upload_to='documents/abha/')),
                ('disease', models.TextField(blank=True)),
                ('alive_status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], default='Alive', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.family')),
            ],
        ),
    ]
