# Generated by Django 5.2.17 on 2026-09-20 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('total_houses', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='family',
            name='house_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='family',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='core.village'),
        ),
    ]
