# Generated by Django 5.2.17 on 2026-09-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pregnancy_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
