# Generated by Django 6.1.1 on 2026-10-07 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_pregnancy_alert_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present (Full Day)'), ('Half Day', 'Half Day'), ('Field Duty', 'Field Duty / Home Visits'), ('Camp Duty', 'Immunization / Health Camp'), ('On Leave', 'On Leave / Holiday')], default='Present', max_length=30)),
                ('duty_type', models.CharField(choices=[('Routine Sub-Center Duty', 'Routine Sub-Center Duty'), ('Home Visits & Door-to-Door Survey', 'Home Visits & Door-to-Door Survey'), ('Maternal & Child Health Checkup', 'Maternal & Child Health Checkup'), ('Pulse Polio / Immunization Drive', 'Pulse Polio / Immunization Drive'), ('Ayushman / ABHA Registration Camp', 'Ayushman / ABHA Registration Camp'), ('PHC / CHC Meeting & Training', 'PHC / CHC Meeting & Training'), ('Emergency Response', 'Emergency Response'), ('Other', 'Other Duty')], default='Routine Sub-Center Duty', max_length=60)),
                ('home_visits_count', models.PositiveIntegerField(default=0)),
                ('patients_attended', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.TextField(blank=True, help_text='Summary of work completed today')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.village')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-check_in_time'],
            },
        ),
    ]
